version: '3.5'
services:
  proposta-app:
    image: msproposta:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      rabbit-mq:
          condition: service_healthy
    ports:
      - "8080:8080"

  notificacao-app:
    image: msnotificacao:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      rabbit-mq:
        condition: service_healthy

  analisecredito-app:
    image: msanalisedecredito:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      rabbit-mq:
        condition: service_healthy

  rabbit-mq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      timeout: 5s
      interval: 5s
      retries: 3

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: propostadb